name : Test Code Format
on:
  pull_request:
    branches:
      -master
jobs:
  testing:
    name: Lint Check and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
          with:
            distribution: 'temurin'
            java-version: 17
      - name: Run Kotlin Linter
        run : ./gradlew ktlintCheck
      - name: Run Android Linter
        run: ./gradlew lintDebug
